// modules/logs/action-type.enum.ts

export enum ActionTypeEnum {
    TRANSFER_TO_SHELF = "TRANSFER_TO_SHELF",
    TRANSFER_TO_WAREHOUSE = "TRANSFER_TO_WAREHOUSE",
    TRANSFER_TO_TRASH = "TRANSFER_TO_TRASH",
    ADD_TO_CART = "ADD_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",
    CHECKOUT = "CHECKOUT",
    CANCEL_CHECKOUT = "CANCEL_CHECKOUT",
    ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT",
    REMOVE_PRODUCT = "REMOVE_PRODUCT",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    ADD_CATEGORY = "ADD_CATEGORY",
    REMOVE_CATEGORY = "REMOVE_CATEGORY",
    UPDATE_CATEGORY = "UPDATE_CATEGORY",
    ADD_USER = "ADD_USER",
    REMOVE_USER = "REMOVE_USER",
    UPDATE_USER = "UPDATE_USER",
}
