import * as React from 'react';
import type { Metadata } from 'next';
import './globals.css';
// import { Head, Html, Main, NextScript } from 'next/document';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};
export default RootLayout;
