stages:
  - dev
  - prod
  - mobile
  - release
  - rollback

trigger-dev:
  stage: dev
  tags:
    - main
  trigger:
    include:
      - local: '/gitlab/ci/dev.yml'
    strategy: depend

trigger-prod:
  stage: prod
  tags:
    - main
  trigger:
    include:
      - local: '/gitlab/ci/prod.yml'
    strategy: depend

trigger-mobile:
  stage: mobile
  tags:
    - main
  trigger:
    include:
      - local: '/gitlab/ci/mobile.yml'
    strategy: depend

trigger-release:
  stage: release
  tags:
    - main
  trigger:
    include:
      - local: '/gitlab/ci/release.yml'
    strategy: depend

trigger-rollback:
  stage: rollback
  tags:
    - main
  trigger:
    include:
      - local: '/gitlab/ci/rollback.yml'
    strategy: depend
