stages:
  - trigger-pipelines
  - build-mobile
  - test-auto-mobile
  - release
  - release-mobile
  - rollback

trigger-dev-pipeline:
  stage: trigger-pipelines
  trigger:
    include: '/gitlab/ci/dev.yml'
    strategy: depend

trigger-prod-pipeline:
  stage: trigger-pipelines
  trigger:
    include: '/gitlab/ci/prod.yml'
    strategy: depend

include:
  - '/gitlab/ci/mobile.yml'
  - '/gitlab/ci/release.yml'
  - '/gitlab/ci/release-mobile.yml'
  - '/gitlab/ci/rollback.yml'
