stages:
  - dev
  - prod
  - release
  - rollback

trigger-dev:
  stage: dev
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
  trigger:
    include:
      - local: '/gitlab/ci/dev.yml'
    strategy: depend

trigger-prod:
  stage: prod
  rules:
    - if: "$CI_COMMIT_TAG"
      when: always
  trigger:
    include:
      - local: '/gitlab/ci/prod.yml'
    strategy: depend

trigger-release:
  stage: release
  rules:
    - if: "$CI_COMMIT_TAG"
      when: always
  trigger:
    include:
      - local: '/gitlab/ci/release.yml'
    strategy: depend

trigger-rollback:
  stage: rollback
  rules:
    - if: "$CI_COMMIT_TAG"
      when: always
  trigger:
    include:
      - local: '/gitlab/ci/rollback.yml'
    strategy: depend
