stages:
  - test
  - build
  - deploy

# Define default image if not specified in jobs
default:
  image: docker:latest
  services:
    - docker:dind

# Test Stage
test:
  stage: test
  script:
    - echo "Running tests..."
    - ls -la
    - cd app
    - ls -la
    - sudo docker build -t app-test -f Dockerfile.prod .
    - sudo docker run --rm app-test sh -c "deno test --allow-import --allow-net --allow-run --allow-read --allow-env"
  only:
    - main
    - dev

# Build Stage
build:
  stage: build
  script:
    - echo "Building Docker image..."
    - ls -la
    - cd app
    - sudo docker build -t app-image -f Dockerfile.prod .
  artifacts:
    name: "app-image"
    paths:
      - ./  # Store your build artifacts, adjust path as needed
  only:
    - main
    - dev

# Deploy Stage
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - sleep 5
    - echo "Deployed!"
  only:
    - main
