stages:
  - test-build
  - test
  - deploy-build
  - deploy-green
  - test-green
  - deploy-blue
  - rollback

default:
  image: docker:latest
  services:
    - docker:dind

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $BLUE_SERVER_IP $GREEN_SERVER_IP $LOAD_BALANCER_IP >> ~/.ssh/known_hosts

# Stage 1: Build the dev environment for testing
test-build:
  stage: test-build
  script:
    - echo "Building test environment..."
    - docker build -t my-app-backend-dev -f ./backend/Dockerfile.dev ./backend
    - docker build -t my-app-frontend-dev -f ./frontend/Dockerfile.dev ./frontend

# Stage 2: Run tests
test:
  stage: test
  script:
    - echo "Running backend tests..."
    - docker run --rm my-app-backend-dev deno test
    - echo "Running frontend tests..."
    - docker run --rm my-app-frontend-dev npm run test

# Stage 3: Build the prod environment for deployment
deploy-build:
  stage: deploy-build
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - echo "Reading current version..."
    - PREVIOUS_VERSION=$(cat VERSION)
    - echo "Previous version= $PREVIOUS_VERSION"

    # Increment version
    - IFS='.' read -r MAJOR MINOR PATCH <<< "$PREVIOUS_VERSION"
    - PATCH=$((PATCH + 1))
    - NEW_VERSION="$MAJOR.$MINOR.$PATCH"
    - echo "$NEW_VERSION" > VERSION
    - echo "New version= $NEW_VERSION"

    # Commit and push the updated VERSION file
    - git config --global user.email "ci@yourdomain.com"
    - git config --global user.name "CI Runner"
    - git add VERSION
    - git commit -m "CI= Increment version to $NEW_VERSION"

    # Build and tag Docker images
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$NEW_VERSION" -f ./backend/Dockerfile.prod ./backend
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$NEW_VERSION" -f ./frontend/Dockerfile.prod ./frontend
    - docker tag "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$NEW_VERSION" "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest"
    - docker tag "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$NEW_VERSION" "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest"

    # Push Docker images
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$NEW_VERSION"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$NEW_VERSION"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest"

  artifacts:
    paths:
      - VERSION
      - PREVIOUS_VERSION

# Stage 4: Deploy to Green environment
deploy-green:
  stage: deploy-green
  script:
    - echo "Deploying to Green environment..."
    - VERSION=$(cat VERSION)
    - echo "Deploying version $VERSION to Green environment..."
    - ssh $DEPLOY_USER_GREEN@$GREEN_SERVER_IP "
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$VERSION &&
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$VERSION &&
      docker stop backend || true && docker stop frontend || true &&
      docker rm backend || true && docker rm frontend || true &&
      docker run -d --name backend -p 4000:4000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$VERSION &&
      docker run -d --name frontend -p 80:3000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$VERSION
      "

# Stage 5: Test Green environment
test-green:
  stage: test-green
  script:
    - echo "Performing health checks on Green environment..."
    - curl -f http://$GREEN_SERVER_IP:4000/health || (echo 'Green environment health check failed!' && exit 1)
    - echo "Green environment is healthy."

# Stage 6: Deploy to Blue environment
deploy-blue:
  stage: deploy-blue
  script:
    - echo "Deploying to Blue environment..."
    - VERSION=$(cat VERSION)
    - echo "Deploying version $VERSION to Blue environment..."
    - ssh $DEPLOY_USER_BLUE@$BLUE_SERVER_IP "
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$VERSION &&
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$VERSION &&
      docker stop backend || true && docker stop frontend || true &&
      docker rm backend || true && docker rm frontend || true &&
      docker run -d --name backend -p 4000:4000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$VERSION &&
      docker run -d --name frontend -p 80:3000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$VERSION
      "

# Stage 7: Rollback in case of failure
rollback:
  stage: rollback
  script:
    - echo "Rolling back Green environment..."
    - VERSION=$(cat VERSION) # Use the current VERSION
    - ssh $DEPLOY_USER_GREEN@$GREEN_SERVER_IP "
      docker stop backend || true && docker stop frontend || true &&
      docker rm backend || true && docker rm frontend || true &&
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$PREVIOUS_VERSION &&
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$PREVIOUS_VERSION &&
      docker run -d --name backend -p 4000:4000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:$PREVIOUS_VERSION &&
      docker run -d --name frontend -p 80:3000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:$PREVIOUS_VERSION
      "
    - echo "Rollback to version $PREVIOUS_VERSION completed."
  when: on_failure
