stages:
  - build-dev-backend
  - build-dev-frontend
  - deploy-dev-backend
  - deploy-dev-frontend
  - test-dev-backend
  - test-dev-frontend
  - build-prod-backend
  - build-prod-frontend
  - deploy-prod-backend
  - deploy-prod-frontend
  - test-prod-backend
  - test-prod-frontend
  - rollback

include:
  - '/gitlab/ci/dev.yml'
  - '/gitlab/ci/prod.yml'
  - '/gitlab/ci/rollback.yml'
