stages:
  - trigger-dev
  - trigger-prod-mobile
  - release
  - rollback

trigger-dev:
  stage: trigger-dev
  trigger:
    include:
      - local: '/gitlab/ci/dev.yml'
    strategy: depend

trigger-prod-mobile:
  stage: trigger-prod-mobile
  trigger:
    include:
      - local: '/gitlab/ci/prod.yml'
      - local: '/gitlab/ci/mobile.yml'
    strategy: depend

trigger-release:
  stage: release
  trigger:
    include:
      - local: '/gitlab/ci/release.yml'
    strategy: depend

trigger-rollback:
  stage: rollback
  trigger:
    include:
      - local: '/gitlab/ci/rollback.yml'
    strategy: depend
