stages:
  - trigger-dev
  - trigger-prod-mobile
  - release
  - rollback

trigger-dev:
  stage: trigger-dev
  script:
    - echo "Triggering Dev pipeline..."
  trigger:
    include:
      - local: '/gitlab/ci/dev.yml'
    strategy: depend

trigger-prod-mobile:
  stage: trigger-prod-mobile
  script:
    - echo "Triggering Prod and Mobile pipelines..."
  trigger:
    include:
      - local: '/gitlab/ci/prod.yml'
      - local: '/gitlab/ci/mobile.yml'
    strategy: depend

trigger-release:
  stage: release
  script:
    - echo "Triggering Release pipeline..."
  trigger:
    include:
      - local: '/gitlab/ci/release.yml'
    strategy: depend

trigger-rollback:
  stage: rollback
  script:
    - echo "Triggering Rollback pipeline..."
  trigger:
    include:
      - local: '/gitlab/ci/rollback.yml'
    strategy: depend
