# Use the official Deno image
FROM denoland/deno:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy project files to the working directory
COPY . .

# Expose the port that the Deno app will run on
EXPOSE 4000

# Set the entrypoint command to run the Deno app
CMD deno run --allow-net --allow-read --allow-env server.ts
