# Use the official Deno image
FROM denoland/deno:alpine

# Set the working directory inside the container
WORKDIR /app

# Expose the port that the Deno app will run on
EXPOSE 4000

# Set the entrypoint command to run the Deno app
CMD deno run --allow-read --allow-net --allow-env scripts/initDB.ts && deno run --allow-net --allow-read --allow-env server.ts && deno run scripts/seeders.ts