CREATE TABLE "Addresses" (
  "addressId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" int,
  "addressLine1" varchar,
  "addressLine2" varchar,
  "addressComplement" varchar,
  "zipCode" varchar,
  "city" varchar,
  "country" varchar
);

CREATE TABLE "Users" (
  "userId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "password" varchar,
  "firstName" varchar,
  "lastName" varchar,
  "phoneNumber" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp,
  "deletedAt" timestamp,
  "roleId" int
);

CREATE TABLE "Roles" (
  "roleId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "Invoices" (
  "invoiceId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" int,
  "addressId" int,
  "createdAt" timestamp
);

CREATE TABLE "InvoiceLines" (
  "invoiceLineId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" varchar,
  "quantity" int,
  "price" decimal,
  "invoiceId" int,
  "createdAt" timestamp
);

CREATE TABLE "Products" (
  "productId" varchar PRIMARY KEY,
  "price" decimal,
  "stockWarehouse" int,
  "stockShelfBottom" int,
  "minimumStock" int,
  "minimumShelfStock" int,
  "taxCategoryId" int
);

CREATE TABLE "TaxCategory" (
  "taxCategoryId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" decimal,
  "description" varchar
);

CREATE TABLE "Logs" (
  "stockLogId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" timestamp,
  "userId" int,
  "productId" varchar,
  "stockTypeId" int,
  "actionId" int,
  "quantity" int,
  "operation" varchar,
  "reason" varchar
);

CREATE TABLE "StockType" (
  "stockTypeId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar
);

CREATE TABLE "Actions" (
  "actionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar
);

ALTER TABLE "Addresses" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("userId");

ALTER TABLE "Users" ADD FOREIGN KEY ("roleId") REFERENCES "Roles" ("roleId");

ALTER TABLE "Invoices" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("userId");

ALTER TABLE "Invoices" ADD FOREIGN KEY ("addressId") REFERENCES "Addresses" ("addressId");

ALTER TABLE "InvoiceLines" ADD FOREIGN KEY ("productId") REFERENCES "Products" ("productId");

ALTER TABLE "InvoiceLines" ADD FOREIGN KEY ("invoiceId") REFERENCES "Invoices" ("invoiceId");

ALTER TABLE "Products" ADD FOREIGN KEY ("taxCategoryId") REFERENCES "TaxCategory" ("taxCategoryId");

ALTER TABLE "Logs" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("userId");

ALTER TABLE "Logs" ADD FOREIGN KEY ("productId") REFERENCES "Products" ("productId");

ALTER TABLE "Logs" ADD FOREIGN KEY ("stockTypeId") REFERENCES "StockType" ("stockTypeId");

ALTER TABLE "Logs" ADD FOREIGN KEY ("actionId") REFERENCES "Actions" ("actionId");
