# dev.yml

build-dev-backend:
  stage: build-dev-backend
  script:
    - echo "Building backend for Dev environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend-dev:latest" -f ./backend/Dockerfile.dev ./backend

build-dev-frontend:
  stage: build-dev-frontend
  script:
    - echo "Building frontend for Dev environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend-dev:latest" -f ./frontend/Dockerfile.dev ./frontend

test-auto-dev-backend:
  stage: test-auto-dev-backend
  dependencies:
    - build-dev-backend
  script:
    - echo "Running automated tests for Dev backend..."
    - cd backend
    - npm install
    - npm test

test-auto-dev-frontend:
  stage: test-auto-dev-frontend
  dependencies:
    - build-dev-frontend
  script:
    - echo "Running automated tests for Dev frontend..."
    - cd frontend
    - npm install
    - npm test

deploy-dev:
  stage: deploy-dev
  dependencies:
    - test-auto-dev-backend
    - test-auto-dev-frontend
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $LOAD_BALANCER_IP >> ~/.ssh/known_hosts
  script:
    - echo "Deploying Dev environment..."
    # Push images
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend-dev:latest"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend-dev:latest"
    # Pull images on server
    - ssh $DEPLOY_USER_LOADB@$LOAD_BALANCER_IP "
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend-dev:latest &&
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend-dev:latest &&
      docker stop dev-backend || true &&
      docker rm dev-backend || true &&
      docker run -d --name dev-backend -p 4000:4000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend-dev:latest &&
      docker stop dev-frontend || true &&
      docker rm dev-frontend || true &&
      docker run -d --name dev-frontend -p 3000:3000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend-dev:latest
      "

test-request-dev-backend:
  stage: test-request-dev-backend
  dependencies:
    - deploy-dev
  script:
    - echo "Testing requests on Dev backend..."
    - curl -f http://$LOAD_BALANCER_IP:4000/health || (echo 'Dev backend health check failed!' && exit 1)

test-request-dev-frontend:
  stage: test-request-dev-frontend
  dependencies:
    - deploy-dev
  script:
    - echo "Testing requests on Dev frontend..."
    - curl -f http://$LOAD_BALANCER_IP:3000 || (echo 'Dev frontend health check failed!' && exit 1)
