stages:
  - build-dev-backend
  - build-dev-frontend
  - test-backend
  - test-frontend
  - deploy-dev
  - test-request-dev-backend
  - test-request-dev-frontend

variables:
  DOCKER_TLS_CERTDIR: ""  # Disable Docker-in-Docker TLS if not needed

build-dev-backend:
  stage: build-dev-backend
  script:
    - echo "Building backend for Dev environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend-dev:latest" -f ./backend/Dockerfile.dev ./backend

build-dev-frontend:
  stage: build-dev-frontend
  script:
    - echo "Building frontend for Dev environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend-dev:latest" -f ./frontend/Dockerfile.dev ./frontend

test-backend:
  stage: test-backend
  script:
    - echo "Running backend tests during Dev pipeline..."
    - docker build --target tester -t backend-tester -f ./backend/Dockerfile.dev ./backend
    - docker run --rm backend-tester

test-frontend:
  stage: test-frontend
  script:
    - echo "Running frontend tests during Dev pipeline..."
    - docker build --target tester -t frontend-tester -f ./frontend/Dockerfile.dev ./frontend
    - docker run --rm frontend-tester

deploy-dev:
  stage: deploy-dev
  script:
    - echo "Deploying Dev environment..."
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend-dev:latest"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend-dev:latest"
    - ssh $DEPLOY_USER_LOADB@$LOAD_BALANCER_IP "
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend-dev:latest &&
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend-dev:latest &&
      docker stop dev-backend || true &&
      docker rm dev-backend || true &&
      docker run -d --name dev-backend -p 4000:4000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend-dev:latest &&
      docker stop dev-frontend || true &&
      docker rm dev-frontend || true &&
      docker run -d --name dev-frontend -p 3000:3000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend-dev:latest
      "

test-request-dev-backend:
  stage: test-request-dev-backend
  script:
    - echo "Testing requests on Dev backend..."
    - curl -f http://$LOAD_BALANCER_IP:4000/health || (echo 'Dev backend health check failed!' && exit 1)

test-request-dev-frontend:
  stage: test-request-dev-frontend
  script:
    - echo "Testing requests on Dev frontend..."
    - curl -f http://$LOAD_BALANCER_IP:3000 || (echo 'Dev frontend health check failed!' && exit 1)
