stages:
  - build-mobile
  - test-auto-mobile

variables:
  ANDROID_SDK_ROOT: "/sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Xmx2g -XX:MaxMetaspaceSize=512m"

build-mobile:
  stage: build-mobile
  script:
    - echo "Building mobile application (React Native)..."
    - cd mobile
    - npm install
    - npm run android-release
    - echo "APK built successfully."
  artifacts:
    paths:
      - mobile/android/app/build/outputs/apk/release/app-release.apk
    expire_in: 1 week

test-auto-mobile:
  stage: test-auto-mobile
  dependencies:
    - build-mobile
  script:
    - echo "Running automated tests for mobile..."
    - cd mobile
    - npm install
    - npm test
