stages:
  - build-prod
  - push-prod-green
  - validate-green
  - push-prod-blue
  - validate-blue

before_script:
  - echo "Logging into Docker Container Registry..."
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20-dind

build-prod-backend:
  stage: build-prod
  script:
    - echo "Building backend for Prod environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:green" -f ./backend/Dockerfile.prod ./backend

build-prod-frontend:
  stage: build-prod

  script:
    - echo "Building frontend for Prod environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:green" -f ./frontend/Dockerfile.prod ./frontend

push-prod-green:
  stage: push-prod-green
  script:
    - echo "Pushing Prod images with 'green' tag..."
    - docker tag "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:green" "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:green"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:green"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest"

validate-backend-green:
  stage: validate-green
  script:
    - echo "Validating Green backend..."
    - apk add --no-cache curl
#    - curl -f http://$GREEN_SERVER_IP:4000/health || (echo 'Green backend health check failed!' && exit 1)

validate-frontend-green:
  stage: validate-green
  script:
    - echo "Validating Green frontend..."
    - apk add --no-cache curl
#    - curl -f http://$GREEN_SERVER_IP:3000 || (echo 'Green frontend health check failed!' && exit 1)

push-prod-blue:
  stage: push-prod-blue
  script:
    - echo "Pushing Prod images with 'blue' tag..."
    - docker tag "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:green" "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:blue"
    - docker tag "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:green" "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:blue"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:blue"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:blue"

validate-backend-blue:
  stage: validate-blue
  script:
    - echo "Validating Blue backend..."
    - apk add --no-cache curl
#    - curl -f http://$BLUE_SERVER_IP:4000/health || (echo 'Blue backend health check failed!' && exit 1)

validate-frontend-blue:
  stage: validate-blue
  script:
    - echo "Validating Blue frontend..."
    - apk add --no-cache curl
#    - curl -f http://$BLUE_SERVER_IP:3000 || (echo 'Blue frontend health check failed!' && exit 1)
