build-prod-backend:
  stage: build-prod-backend
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - echo "Building backend Docker image for Prod environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest" -f ./backend/Dockerfile.prod ./backend
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest"

build-prod-frontend:
  stage: build-prod-frontend
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - echo "Building frontend Docker image for Prod environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest" -f ./frontend/Dockerfile.prod ./frontend
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest"

deploy-prod-backend:
  stage: deploy-prod-backend
  dependencies:
    - build-prod-backend
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $BLUE_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "Deploying backend Prod environment..."
    - ssh $DEPLOY_USER_BLUE@$BLUE_SERVER_IP "
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest &&
      docker stop prod-backend || true &&
      docker rm prod-backend || true &&
      docker run -d --name prod-backend -p 4000:4000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest
      "

deploy-prod-frontend:
  stage: deploy-prod-frontend
  dependencies:
    - build-prod-frontend
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $BLUE_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "Deploying frontend Prod environment..."
    - ssh $DEPLOY_USER_BLUE@$BLUE_SERVER_IP "
      docker pull $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest &&
      docker stop prod-frontend || true &&
      docker rm prod-frontend || true &&
      docker run -d --name prod-frontend -p 3000:3000 $DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest
      "
