stages:
  - build-prod-backend
  - build-prod-frontend
  - test-backend
  - test-frontend
  - push-prod
  - deploy-prod-green
  - test-request-prod-backend-green
  - test-request-prod-frontend-green
  - deploy-prod-blue
  - test-request-prod-backend-blue
  - test-request-prod-frontend-blue

variables:
  DOCKER_TLS_CERTDIR: ""  # Disable Docker-in-Docker TLS if not needed

build-prod-backend:
  stage: build-prod-backend
  script:
    - echo "Building backend for Prod environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest" -f ./backend/Dockerfile.prod ./backend

build-prod-frontend:
  stage: build-prod-frontend
  script:
    - echo "Building frontend for Prod environment..."
    - docker build -t "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest" -f ./frontend/Dockerfile.prod ./frontend

test-backend:
  stage: test-backend
  script:
    - echo "Running backend tests during Prod pipeline..."
    - docker build --target tester -t backend-tester -f ./backend/Dockerfile.prod ./backend
    - docker run --rm backend-tester

test-frontend:
  stage: test-frontend
  script:
    - echo "Running frontend tests during Prod pipeline..."
    - docker build --target tester -t frontend-tester -f ./frontend/Dockerfile.prod ./frontend
    - docker run --rm frontend-tester

push-prod:
  stage: push-prod
  script:
    - echo "Pushing Prod images..."
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-backend:latest"
    - docker push "$DOCKER_NAMESPACE/$DOCKER_REPOSITORY-frontend:latest"

# Rest of the stages remain unchanged...
