export const data = [
  {
    id: 1,
    name: 'fishy Box',
    ean: '1234567890123',
    description: 'fish',
    brand: 'sea',
    conditioning: 'box',
    weight: '100 grams',
    categories: ['food', 'fish'],
  },
  {
    id: 2,
    name: 'meaty Box',
    ean: '9876543210987',
    description: 'meat',
    brand: 'land',
    conditioning: 'box',
    weight: '200 grams',
    categories: ['food', 'meat'],
  },
  {
    id: 3,
    name: 'veggie Box',
    ean: '1234567890123',
    description: 'vegetables',
    brand: 'farm',
    conditioning: 'box',
    weight: '300 grams',
    categories: ['food', 'vegetables'],
  },
  {
    id: 4,
    name: 'fruity Box',
    ean: '9876543210987',
    description: 'fruits',
    brand: 'orchard',
    conditioning: 'box',
    weight: '400 grams',
    categories: ['food', 'fruits'],
  },
  {
    id: 5,
    name: 'dairy Box',
    ean: '1234567890123',
    description: 'dairy',
    brand: 'farm',
    conditioning: 'box',
    weight: '500 grams',
    categories: ['food', 'dairy'],
  },
];
